# Manual least squares in np

April 18, 2021

Doesn't make sense to use pandas in pygame... so will try to work this out in np

In [1]:
import numpy as np
import pandas as pd 

In [2]:
arr = np.load('../data/basic_arr.npy')

### 1. Configure the data

In [5]:
x_mean = arr[:,0].mean()
y_mean = arr[:,1].mean()

x_mean, y_mean

(74.0, 10.0)

### 2. Get x and y deviations

In [16]:
x_dev = arr[:,0] - x_mean
y_dev = arr[:,1] - y_mean

x_dev, y_dev

(array([-40.,  34., -10.,  14.,  25., -23.]),
 array([-5.,  7.,  1., -2.,  4., -5.]))

### 3. Deviation products

In [17]:
numerator = x_dev * y_dev

### 4. Square of x deviation

In [18]:
denom = x_dev**2
denom

array([1600., 1156.,  100.,  196.,  625.,  529.])

### 5. Get slope

In [19]:
numerator.sum(), denom.sum()

(615.0, 4206.0)

In [20]:
slope = numerator.sum()/denom.sum()

slope

0.14621968616262482

## This matches ^^

## Now, to get RSS

- y = b0 + b1*x
- b0 = y - b1*x

In [27]:
b1 = slope
b1

0.14621968616262482

In [26]:
b0 = y_mean - b1*x_mean
b0

-0.8202567760342365

## Get SSE -- sum of squared errors

#### First, predict each x

In [28]:
pred = b0 + b1*arr[:,0]
pred

array([ 4.15121255, 14.97146933,  8.53780314, 12.04707561, 13.65549215,
        6.63694722])

In [29]:
error = arr[:,1] - pred
error

array([ 0.84878745,  2.02853067,  2.46219686, -4.04707561,  0.34450785,
       -1.63694722])

In [30]:
squared_error = error**2
squared_error

array([ 0.72044013,  4.11493668,  6.06241339, 16.37882096,  0.11868566,
        2.6795962 ])

In [31]:
SSE = squared_error.sum()
SSE

30.074893009985736