# Sandbox 1

April 9, 2021

## Scale the axes

In [1]:
import numpy as np

In [3]:
np.arange(2, 23, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [12]:
arr = np.linspace(2,10,10).round(1)

arr

array([ 2. ,  2.9,  3.8,  4.7,  5.6,  6.4,  7.3,  8.2,  9.1, 10. ])

In [15]:
x_min = 34
x_max = 108
num_scales = 20

arr = np.linspace(x_min, x_max, num_scales).round(1)
arr

array([ 34. ,  37.9,  41.8,  45.7,  49.6,  53.5,  57.4,  61.3,  65.2,
        69.1,  72.9,  76.8,  80.7,  84.6,  88.5,  92.4,  96.3, 100.2,
       104.1, 108. ])

In [16]:
for item in arr:
    print(item)

34.0
37.9
41.8
45.7
49.6
53.5
57.4
61.3
65.2
69.1
72.9
76.8
80.7
84.6
88.5
92.4
96.3
100.2
104.1
108.0


In [19]:
arr[0]


34.0

## Import basic np array

In [20]:
arr = np.load('data/basic_arr.npy')

In [21]:
arr

array([[ 34,   5],
       [108,  17],
       [ 64,  11],
       [ 88,   8],
       [ 99,  14],
       [ 51,   5]], dtype=int64)

In [25]:
arr[0][0]

34

In [26]:
arr[1][0]

108

In [32]:
arr2 = arr[arr[:, 0].argsort()]
arr2

array([[ 34,   5],
       [ 51,   5],
       [ 64,  11],
       [ 88,   8],
       [ 99,  14],
       [108,  17]], dtype=int64)

In [35]:
arr[:,0].min()

34

In [37]:
x_scale = np.linspace( (arr[:,0].min() ), (arr[:,0].max() ), 20).round(1)
x_scale

array([ 34. ,  37.9,  41.8,  45.7,  49.6,  53.5,  57.4,  61.3,  65.2,
        69.1,  72.9,  76.8,  80.7,  84.6,  88.5,  92.4,  96.3, 100.2,
       104.1, 108. ])

In [38]:
x_scale[1] - x_scale[0]

3.8999999999999986