# USA Housing dataset
April 5, 2021

- Want to convert this to a simple dataset for import to my pygame program
- I believe number of bedrooms (x) predicts house price (y)

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

sns.set()

In [4]:
df = pd.read_csv('USA_Housing.csv')

In [7]:
df.head(3)

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avg. Area Income              5000 non-null   float64
 1   Avg. Area House Age           5000 non-null   float64
 2   Avg. Area Number of Rooms     5000 non-null   float64
 3   Avg. Area Number of Bedrooms  5000 non-null   float64
 4   Area Population               5000 non-null   float64
 5   Price                         5000 non-null   float64
 6   Address                       5000 non-null   object 
dtypes: float64(6), object(1)
memory usage: 273.6+ KB


In [10]:
df.columns

Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price', 'Address'],
      dtype='object')

In [11]:
df2 = df

In [13]:
df = df2[['Avg. Area Number of Bedrooms', 'Price']]

In [15]:
df.head(3)

Avg. Area Number of Bedrooms         Price
0                          4.09  1.059034e+06
1                          3.09  1.505891e+06
2                          5.13  1.058988e+06

In [18]:
df.rename(columns = {'Avg. Area Number of Bedrooms': 'bedooms'}, inplace = True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4133: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [19]:
df.head(3)

bedooms         Price
0     4.09  1.059034e+06
1     3.09  1.505891e+06
2     5.13  1.058988e+06

In [20]:
df.rename(columns = {'Price': 'price'}, inplace = True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4133: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [21]:
df.head(3)

bedooms         price
0     4.09  1.059034e+06
1     3.09  1.505891e+06
2     5.13  1.058988e+06

## Get a sample of 200 rows

In [23]:
df = df.sample(n=200)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 200 entries, 4472 to 3631
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   bedooms  200 non-null    float64
 1   price    200 non-null    float64
dtypes: float64(2)
memory usage: 4.7 KB


In [27]:
df.head()

bedooms         price
4472     3.48  9.746000e+05
474      5.47  1.137059e+06
4357     2.03  4.813916e+05
101      2.02  1.114431e+06
4828     5.46  1.735417e+06

## Convert to numpy array

In [25]:
arr = df.to_numpy()

In [28]:
arr[:10]

array([[3.48000000e+00, 9.74599959e+05],
       [5.47000000e+00, 1.13705919e+06],
       [2.03000000e+00, 4.81391643e+05],
       [2.02000000e+00, 1.11443095e+06],
       [5.46000000e+00, 1.73541692e+06],
       [3.36000000e+00, 1.24211143e+06],
       [4.37000000e+00, 1.44347004e+06],
       [3.46000000e+00, 1.09770194e+06],
       [3.24000000e+00, 1.26518091e+06],
       [6.46000000e+00, 1.21004674e+06]])

## Save numpy array

In [31]:
np.save("usa_housing", arr)

## Get some data to scale the axes

In [34]:
df.price.describe()

count    2.000000e+02
mean     1.227220e+06
std      3.726019e+05
min      3.114052e+04
25%      9.957257e+05
50%      1.241075e+06
75%      1.466004e+06
max      1.967637e+06
Name: price, dtype: float64

In [35]:
df.price.max()

1967637.286822351

In [37]:
df.price.min()

31140.517620186045

#### I am predicting house price based on number of bedrooms
- So, price = y axis
- A reasonable y axis in pygame / pixels is 600

In [39]:
factor = df.price.max()/600
factor

3279.3954780372515

In [41]:
df.price.min() / factor

9.495810379913047

 Okay -- so the smallest house will be 9 pixels above 0, and the largest will be 600

### X axis

In [46]:
df.rename(columns = {'bedooms': 'beds'}, inplace=True)

In [47]:
df.beds.max()

6.5

In [48]:
df.beds.min()

2.02

#### A reasonable x axis would be 1000

In [49]:
xfactor = df.beds.max() / 1000
xfactor 

0.0065

In [51]:
xfactor = 1/xfactor
xfactor

153.84615384615384

In [52]:
df.beds.max() * xfactor

1000.0

In [53]:
df.beds.min() * xfactor

310.7692307692308

## Sum of factors

- Divide all y values by 3300
- Multiply all x values by 150

## How to perform operations on numpy array columns

In [54]:
arr[0]

array([3.48000000e+00, 9.74599959e+05])

In [55]:
arr[:3]

array([[3.48000000e+00, 9.74599959e+05],
       [5.47000000e+00, 1.13705919e+06],
       [2.03000000e+00, 4.81391643e+05]])

In [81]:
beds = arr[:,0] * 150
beds

array([522. , 820.5, 304.5, 303. , 819. , 504. , 655.5, 519. , 486. ,
       969. , 619.5, 450. , 637.5, 931.5, 762. , 453. , 475.5, 468. ,
       508.5, 757.5, 355.5, 477. , 354. , 966. , 322.5, 673.5, 640.5,
       954. , 643.5, 519. , 340.5, 657. , 792. , 465. , 474. , 474. ,
       366. , 309. , 954. , 472.5, 955.5, 486. , 957. , 373.5, 630. ,
       462. , 483. , 774. , 478.5, 313.5, 487.5, 307.5, 483. , 504. ,
       624. , 453. , 507. , 667.5, 948. , 790.5, 949.5, 610.5, 492. ,
       669. , 601.5, 624. , 513. , 456. , 654. , 471. , 628.5, 937.5,
       487.5, 624. , 495. , 474. , 621. , 793.5, 756. , 613.5, 807. ,
       810. , 667.5, 613.5, 916.5, 508.5, 759. , 507. , 523.5, 609. ,
       496.5, 453. , 673.5, 346.5, 664.5, 633. , 663. , 495. , 928.5,
       625.5, 369. , 618. , 453. , 505.5, 669. , 604.5, 343.5, 942. ,
       496.5, 325.5, 369. , 460.5, 624. , 451.5, 631.5, 807. , 933. ,
       484.5, 472.5, 349.5, 478.5, 787.5, 606. , 918. , 667.5, 366. ,
       489. , 351. ,

#### Prices

In [72]:
arr[:5]

array([[3.48000000e+00, 9.74599959e+05],
       [5.47000000e+00, 1.13705919e+06],
       [2.03000000e+00, 4.81391643e+05],
       [2.02000000e+00, 1.11443095e+06],
       [5.46000000e+00, 1.73541692e+06]])

In [73]:
arr[:5,1]

array([ 974599.95876417, 1137059.18848432,  481391.64332197,
       1114430.95342313, 1735416.92139243])

In [74]:
prices = arr[:,1] / 3300
prices[:5]

array([295.33332084, 344.56339045, 145.87625555, 337.70634952,
       525.88391557])

## Vector operations on the array

In [75]:
arr[:5]

array([[3.48000000e+00, 9.74599959e+05],
       [5.47000000e+00, 1.13705919e+06],
       [2.03000000e+00, 4.81391643e+05],
       [2.02000000e+00, 1.11443095e+06],
       [5.46000000e+00, 1.73541692e+06]])

In [80]:
arr2 = arr.copy()
arr2[:5]

array([[3.48000000e+00, 9.74599959e+05],
       [5.47000000e+00, 1.13705919e+06],
       [2.03000000e+00, 4.81391643e+05],
       [2.02000000e+00, 1.11443095e+06],
       [5.46000000e+00, 1.73541692e+06]])

#### beds

In [82]:
arr2[:,0] = arr2[:,0] * 150
arr2[:5]

array([[5.22000000e+02, 9.74599959e+05],
       [8.20500000e+02, 1.13705919e+06],
       [3.04500000e+02, 4.81391643e+05],
       [3.03000000e+02, 1.11443095e+06],
       [8.19000000e+02, 1.73541692e+06]])

In [84]:
arr2[:5,0]

array([522. , 820.5, 304.5, 303. , 819. ])

In [83]:
arr2[:,0].max()

975.0

#### prices

In [85]:
arr2[:,1] = arr2[:,1] / 3300

In [86]:
arr2[:,1].max()

596.2537232795003

In [87]:
arr2[:5]

array([[522.        , 295.33332084],
       [820.5       , 344.56339045],
       [304.5       , 145.87625555],
       [303.        , 337.70634952],
       [819.        , 525.88391557]])

## Oh shit -- I think I broke a huge rule of statistics by scaling the axis by different values...

- okay, let's just run with this for now.

## Save different version

In [88]:
np.save("usa_housing_scaled", arr)

## How would I iterate through the list in pygame?

In [90]:
for pair in arr2[:10]:
    beds = int(pair[0])
    price = int(pair[1])
    print(beds, price) 

522 295
820 344
304 145
303 337
819 525
504 376
655 437
519 332
486 383
969 366


## Convert the whole array to int's

In [91]:
arr_int = arr2.astype(int)

In [92]:
arr_int[:5]

array([[522, 295],
       [820, 344],
       [304, 145],
       [303, 337],
       [819, 525]])

In [93]:
np.save("usa_housing_scaled", arr_int)

In [95]:
for pair in arr_int[:10]:
    print(pair)

[522 295]
[820 344]
[304 145]
[303 337]
[819 525]
[504 376]
[655 437]
[519 332]
[486 383]
[969 366]
